# coauthor_count.sparql
#
# This query gets the number of publications two authors have
# published together
#
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bibo:     <http://purl.org/ontology/bibo/>
PREFIX vivo:     <http://vivoweb.org/ontology/core#>

SELECT (count(?Document1) as ?cnt)
WHERE {
    ?Authorship1 rdf:type vivo:Authorship .
    ?Authorship1 vivo:relates <http://vivo.northwestern.edu/individual/ne994246efd> .
    ?Authorship1 vivo:relates ?Document1 .
    ?Document1 rdf:type bibo:Document .
    ?Document1 vivo:relatedBy ?Authorship2 .
    ?Authorship2 rdf:type vivo:Authorship .
    ?Authorship2 vivo:relates <http://vivo.northwestern.edu/individual/nff34c486bf>
}