# orgs_without_labels.sparql
# 
# List all organizations that do not have labels
#
PREFIX foaf:     <http://xmlns.com/foaf/0.1/>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?uri 
WHERE {
  ?uri a foaf:Organization .
  OPTIONAL {?uri rdfs:label ?label .}
  FILTER (!BOUND(?label))
}