# wordle.sparql
#
# Get the title and abstract from an author's publications
# 
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bibo:     <http://purl.org/ontology/bibo/>
PREFIX vivo:     <http://vivoweb.org/ontology/core#>
PREFIX vlocal:   <http://vivo.northwestern.edu/ontology/vlocal#>

SELECT ?publication ?title # ?abstract
WHERE
{
  ?authorship rdf:type vivo:Authorship .
  ?authorship vivo:relates <http://vivo.northwestern.edu/individual/ne994246efd> .
  ?publication vivo:relatedBy ?authorship .
  ?publication rdf:type bibo:Letter .
  ?publication rdfs:label ?title .
  # OPTIONAL { ?publication bibo:abstract ?abstract } .
}
    